version: "3.5"

services:
  # ROS remote development environment
  ros-develop:
    image: iris/ros-develop:0.1
    build:
      context: .
      dockerfile: ./docker/ros-develop.dockerfile
      args:
        REMOTE_KEY: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDSl1UBEK3XAX/WV04Trvc5ukqoxSLMYCg0u0tacaWqYVaOEXBly4fksCqGrkyXx2ZdpJ5AQQbOLC8RT4Z+PFi70ptgcERparFBFt3jSj1Tp5rQoqBh/AMloxSa7zWD5zfys5VJp5WAfUMW3S/5SWNdgDkW3jWojzskDwsytkoCJ0w+LWxTDT1fg3GOOx5j9cUUKbh19qUHOZYryZ7D9NEtyXA0S32WCO3dFqFvuaEWXCUdmpBjncfxdgKDhCPFttbiBh2jJQ2hlKY3oD/UaWYSJ9zUppyR32vbsdyftW/Qda7dCWRydgvKmbJT1MghEEj1RkM+eL/xPD+LXl9yCSI7 dhruv@dhruv
    privileged: true
    tty: true
    environment:
      - "ROS_MASTER_URI=${ROS_MASTER_URI}"
      - "ROS_HOSTNAME=${ROS_HOSTNAME}"
    volumes:
      - ./storage:/storage
      - ./docs:/docs
    network_mode: host
    # ports:
    #   - "2222:2222" # ssh
    restart: always
